---
#https://github.com/mahdi22/ansible-mariadb-install
- name: Automate MariaDB Setup
  hosts: SQL
  become: true
  vars:
    mariadb_admin_name : "groot"
    mariadb_admin_pass : "sagichdirnicht"

  tasks:
    - name: Install MariaDB Server
      apt:
      name: mariadb-server
      state: present

    - name: Start and Enable MariaDB Service
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Secure Installation (Optional)
      shell: |
        mysql_secure_installation <<EOF
        n
        y
        y
        y
        y
        EOF
      #1 n => Change the root password?
      #4 y => Remove anonymous users?
      #5 y => Disallow root login remotely??
      #6 y => Remove test database and access to it?
      #7 y => Reload privilege tables now?
    
    -name: Set local Admin
      debug:
      shell: |
        mariadb <<EOF
        GRANT ALL ON *.* TO '"{{mariadb_admin_name}}"' IDENTIFIED BY '"{{mariadb_admin_pass}}"'' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        exit